// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:acd61949-423b-4e2a-8e1e-78d79cff5739",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_iSrivCVCh",
    "aws_user_pools_web_client_id": "21dmqan5mkqfd0sbj758iu3ak4"
};


export default awsmobile;
